/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDisputeModule,
  IDisputeModuleInterface,
} from "../../../contracts/TaskMarket.sol/IDisputeModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "disputeURI",
        type: "string",
      },
    ],
    name: "openDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDisputeModule__factory {
  static readonly abi = _abi;
  static createInterface(): IDisputeModuleInterface {
    return new Interface(_abi) as IDisputeModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDisputeModule {
    return new Contract(address, _abi, runner) as unknown as IDisputeModule;
  }
}
