/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Minimal,
  IERC20MinimalInterface,
} from "../../../contracts/TaskMarket.sol/IERC20Minimal";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Minimal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20MinimalInterface {
    return new Interface(_abi) as IERC20MinimalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Minimal {
    return new Contract(address, _abi, runner) as unknown as IERC20Minimal;
  }
}
