/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IListingRegistry,
  IListingRegistryInterface,
} from "../../../contracts/TaskMarket.sol/IListingRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "listingId",
        type: "uint256",
      },
    ],
    name: "getListing",
    outputs: [
      {
        internalType: "uint256",
        name: "agentId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "listingURI",
        type: "string",
      },
      {
        components: [
          {
            internalType: "address",
            name: "paymentToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "basePrice",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "unitType",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "unitPrice",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "minUnits",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "maxUnits",
            type: "uint32",
          },
          {
            internalType: "bool",
            name: "quoteRequired",
            type: "bool",
          },
        ],
        internalType: "struct IListingRegistry.Pricing",
        name: "pricing",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "uint32",
            name: "challengeWindowSec",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "postDisputeWindowSec",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "sellerBondBps",
            type: "uint16",
          },
        ],
        internalType: "struct IListingRegistry.Policy",
        name: "policy",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IListingRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IListingRegistryInterface {
    return new Interface(_abi) as IListingRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IListingRegistry {
    return new Contract(address, _abi, runner) as unknown as IListingRegistry;
  }
}
