/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IListingRegistry {
  export type PricingStruct = {
    paymentToken: AddressLike;
    basePrice: BigNumberish;
    unitType: BytesLike;
    unitPrice: BigNumberish;
    minUnits: BigNumberish;
    maxUnits: BigNumberish;
    quoteRequired: boolean;
  };

  export type PricingStructOutput = [
    paymentToken: string,
    basePrice: bigint,
    unitType: string,
    unitPrice: bigint,
    minUnits: bigint,
    maxUnits: bigint,
    quoteRequired: boolean
  ] & {
    paymentToken: string;
    basePrice: bigint;
    unitType: string;
    unitPrice: bigint;
    minUnits: bigint;
    maxUnits: bigint;
    quoteRequired: boolean;
  };

  export type PolicyStruct = {
    challengeWindowSec: BigNumberish;
    postDisputeWindowSec: BigNumberish;
    sellerBondBps: BigNumberish;
  };

  export type PolicyStructOutput = [
    challengeWindowSec: bigint,
    postDisputeWindowSec: bigint,
    sellerBondBps: bigint
  ] & {
    challengeWindowSec: bigint;
    postDisputeWindowSec: bigint;
    sellerBondBps: bigint;
  };
}

export interface IListingRegistryInterface extends Interface {
  getFunction(nameOrSignature: "getListing"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
}

export interface IListingRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IListingRegistry;
  waitForDeployment(): Promise<this>;

  interface: IListingRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [
      [
        bigint,
        string,
        IListingRegistry.PricingStructOutput,
        IListingRegistry.PolicyStructOutput,
        boolean
      ] & {
        agentId: bigint;
        listingURI: string;
        pricing: IListingRegistry.PricingStructOutput;
        policy: IListingRegistry.PolicyStructOutput;
        active: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [
      [
        bigint,
        string,
        IListingRegistry.PricingStructOutput,
        IListingRegistry.PolicyStructOutput,
        boolean
      ] & {
        agentId: bigint;
        listingURI: string;
        pricing: IListingRegistry.PricingStructOutput;
        policy: IListingRegistry.PolicyStructOutput;
        active: boolean;
      }
    ],
    "view"
  >;

  filters: {};
}
