/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TaskMarket {
  export type TaskStruct = {
    id: BigNumberish;
    listingId: BigNumberish;
    agentId: BigNumberish;
    buyer: AddressLike;
    paymentToken: AddressLike;
    taskURI: string;
    proposedUnits: BigNumberish;
    quotedUnits: BigNumberish;
    quotedTotalPrice: BigNumberish;
    quoteExpiry: BigNumberish;
    fundedAmount: BigNumberish;
    sellerBond: BigNumberish;
    artifactURI: string;
    artifactHash: BytesLike;
    submittedAt: BigNumberish;
    status: BigNumberish;
    settled: boolean;
  };

  export type TaskStructOutput = [
    id: bigint,
    listingId: bigint,
    agentId: bigint,
    buyer: string,
    paymentToken: string,
    taskURI: string,
    proposedUnits: bigint,
    quotedUnits: bigint,
    quotedTotalPrice: bigint,
    quoteExpiry: bigint,
    fundedAmount: bigint,
    sellerBond: bigint,
    artifactURI: string,
    artifactHash: string,
    submittedAt: bigint,
    status: bigint,
    settled: boolean
  ] & {
    id: bigint;
    listingId: bigint;
    agentId: bigint;
    buyer: string;
    paymentToken: string;
    taskURI: string;
    proposedUnits: bigint;
    quotedUnits: bigint;
    quotedTotalPrice: bigint;
    quoteExpiry: bigint;
    fundedAmount: bigint;
    sellerBond: bigint;
    artifactURI: string;
    artifactHash: string;
    submittedAt: bigint;
    status: bigint;
    settled: boolean;
  };
}

export interface TaskMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptQuote"
      | "acceptSubmission"
      | "acceptTask"
      | "cancelTask"
      | "disputeModule"
      | "disputeSubmission"
      | "fundSellerBond"
      | "fundTask"
      | "getTask"
      | "identityRegistry"
      | "listingRegistry"
      | "markDisputed"
      | "owner"
      | "postTask"
      | "proposeQuote"
      | "resolveDispute"
      | "setDisputeModule"
      | "settleAfterTimeout"
      | "submitDeliverable"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliverableSubmitted"
      | "QuoteAccepted"
      | "QuoteProposed"
      | "SellerBondFunded"
      | "SubmissionAccepted"
      | "SubmissionDisputed"
      | "TaskAccepted"
      | "TaskCancelled"
      | "TaskFunded"
      | "TaskPosted"
      | "TaskSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptSubmission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeSubmission",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fundSellerBond",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listingRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postTask",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeQuote",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleAfterTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDeliverable",
    values: [BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundSellerBond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleAfterTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDeliverable",
    data: BytesLike
  ): Result;
}

export namespace DeliverableSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    artifactURI: string,
    artifactHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    artifactURI: string,
    artifactHash: string
  ];
  export interface OutputObject {
    taskId: bigint;
    artifactURI: string;
    artifactHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteAcceptedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteProposedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    quotedUnits: BigNumberish,
    quotedTotalPrice: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    quotedUnits: bigint,
    quotedTotalPrice: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    quotedUnits: bigint;
    quotedTotalPrice: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellerBondFundedEvent {
  export type InputTuple = [taskId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [taskId: bigint, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionAcceptedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionDisputedEvent {
  export type InputTuple = [taskId: BigNumberish, disputeURI: string];
  export type OutputTuple = [taskId: bigint, disputeURI: string];
  export interface OutputObject {
    taskId: bigint;
    disputeURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAcceptedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskFundedEvent {
  export type InputTuple = [taskId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [taskId: bigint, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskPostedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    listingId: BigNumberish,
    agentId: BigNumberish,
    buyer: AddressLike,
    taskURI: string,
    proposedUnits: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    listingId: bigint,
    agentId: bigint,
    buyer: string,
    taskURI: string,
    proposedUnits: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    listingId: bigint;
    agentId: bigint;
    buyer: string;
    taskURI: string;
    proposedUnits: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskSettledEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    buyerPayout: BigNumberish,
    sellerBondRefund: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    buyerPayout: bigint,
    sellerBondRefund: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    buyerPayout: bigint;
    sellerBondRefund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskMarket extends BaseContract {
  connect(runner?: ContractRunner | null): TaskMarket;
  waitForDeployment(): Promise<this>;

  interface: TaskMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptQuote: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  acceptSubmission: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  acceptTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  disputeModule: TypedContractMethod<[], [string], "view">;

  disputeSubmission: TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;

  fundSellerBond: TypedContractMethod<
    [taskId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundTask: TypedContractMethod<
    [taskId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [TaskMarket.TaskStructOutput],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  listingRegistry: TypedContractMethod<[], [string], "view">;

  markDisputed: TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  postTask: TypedContractMethod<
    [listingId: BigNumberish, taskURI: string, proposedUnits: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  proposeQuote: TypedContractMethod<
    [
      taskId: BigNumberish,
      quotedUnits: BigNumberish,
      quotedTotalPrice: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, arg2: string],
    [void],
    "nonpayable"
  >;

  setDisputeModule: TypedContractMethod<
    [disputeModule_: AddressLike],
    [void],
    "nonpayable"
  >;

  settleAfterTimeout: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitDeliverable: TypedContractMethod<
    [taskId: BigNumberish, artifactURI: string, artifactHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptQuote"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptSubmission"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputeSubmission"
  ): TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundSellerBond"
  ): TypedContractMethod<
    [taskId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [TaskMarket.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "listingRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postTask"
  ): TypedContractMethod<
    [listingId: BigNumberish, taskURI: string, proposedUnits: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeQuote"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      quotedUnits: BigNumberish,
      quotedTotalPrice: BigNumberish,
      expiry: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, arg2: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDisputeModule"
  ): TypedContractMethod<[disputeModule_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleAfterTimeout"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitDeliverable"
  ): TypedContractMethod<
    [taskId: BigNumberish, artifactURI: string, artifactHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DeliverableSubmitted"
  ): TypedContractEvent<
    DeliverableSubmittedEvent.InputTuple,
    DeliverableSubmittedEvent.OutputTuple,
    DeliverableSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteAccepted"
  ): TypedContractEvent<
    QuoteAcceptedEvent.InputTuple,
    QuoteAcceptedEvent.OutputTuple,
    QuoteAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteProposed"
  ): TypedContractEvent<
    QuoteProposedEvent.InputTuple,
    QuoteProposedEvent.OutputTuple,
    QuoteProposedEvent.OutputObject
  >;
  getEvent(
    key: "SellerBondFunded"
  ): TypedContractEvent<
    SellerBondFundedEvent.InputTuple,
    SellerBondFundedEvent.OutputTuple,
    SellerBondFundedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionAccepted"
  ): TypedContractEvent<
    SubmissionAcceptedEvent.InputTuple,
    SubmissionAcceptedEvent.OutputTuple,
    SubmissionAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionDisputed"
  ): TypedContractEvent<
    SubmissionDisputedEvent.InputTuple,
    SubmissionDisputedEvent.OutputTuple,
    SubmissionDisputedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAccepted"
  ): TypedContractEvent<
    TaskAcceptedEvent.InputTuple,
    TaskAcceptedEvent.OutputTuple,
    TaskAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskFunded"
  ): TypedContractEvent<
    TaskFundedEvent.InputTuple,
    TaskFundedEvent.OutputTuple,
    TaskFundedEvent.OutputObject
  >;
  getEvent(
    key: "TaskPosted"
  ): TypedContractEvent<
    TaskPostedEvent.InputTuple,
    TaskPostedEvent.OutputTuple,
    TaskPostedEvent.OutputObject
  >;
  getEvent(
    key: "TaskSettled"
  ): TypedContractEvent<
    TaskSettledEvent.InputTuple,
    TaskSettledEvent.OutputTuple,
    TaskSettledEvent.OutputObject
  >;

  filters: {
    "DeliverableSubmitted(uint256,string,bytes32)": TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;
    DeliverableSubmitted: TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;

    "QuoteAccepted(uint256)": TypedContractEvent<
      QuoteAcceptedEvent.InputTuple,
      QuoteAcceptedEvent.OutputTuple,
      QuoteAcceptedEvent.OutputObject
    >;
    QuoteAccepted: TypedContractEvent<
      QuoteAcceptedEvent.InputTuple,
      QuoteAcceptedEvent.OutputTuple,
      QuoteAcceptedEvent.OutputObject
    >;

    "QuoteProposed(uint256,uint32,uint256,uint64)": TypedContractEvent<
      QuoteProposedEvent.InputTuple,
      QuoteProposedEvent.OutputTuple,
      QuoteProposedEvent.OutputObject
    >;
    QuoteProposed: TypedContractEvent<
      QuoteProposedEvent.InputTuple,
      QuoteProposedEvent.OutputTuple,
      QuoteProposedEvent.OutputObject
    >;

    "SellerBondFunded(uint256,uint256)": TypedContractEvent<
      SellerBondFundedEvent.InputTuple,
      SellerBondFundedEvent.OutputTuple,
      SellerBondFundedEvent.OutputObject
    >;
    SellerBondFunded: TypedContractEvent<
      SellerBondFundedEvent.InputTuple,
      SellerBondFundedEvent.OutputTuple,
      SellerBondFundedEvent.OutputObject
    >;

    "SubmissionAccepted(uint256)": TypedContractEvent<
      SubmissionAcceptedEvent.InputTuple,
      SubmissionAcceptedEvent.OutputTuple,
      SubmissionAcceptedEvent.OutputObject
    >;
    SubmissionAccepted: TypedContractEvent<
      SubmissionAcceptedEvent.InputTuple,
      SubmissionAcceptedEvent.OutputTuple,
      SubmissionAcceptedEvent.OutputObject
    >;

    "SubmissionDisputed(uint256,string)": TypedContractEvent<
      SubmissionDisputedEvent.InputTuple,
      SubmissionDisputedEvent.OutputTuple,
      SubmissionDisputedEvent.OutputObject
    >;
    SubmissionDisputed: TypedContractEvent<
      SubmissionDisputedEvent.InputTuple,
      SubmissionDisputedEvent.OutputTuple,
      SubmissionDisputedEvent.OutputObject
    >;

    "TaskAccepted(uint256)": TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;
    TaskAccepted: TypedContractEvent<
      TaskAcceptedEvent.InputTuple,
      TaskAcceptedEvent.OutputTuple,
      TaskAcceptedEvent.OutputObject
    >;

    "TaskCancelled(uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskFunded(uint256,uint256)": TypedContractEvent<
      TaskFundedEvent.InputTuple,
      TaskFundedEvent.OutputTuple,
      TaskFundedEvent.OutputObject
    >;
    TaskFunded: TypedContractEvent<
      TaskFundedEvent.InputTuple,
      TaskFundedEvent.OutputTuple,
      TaskFundedEvent.OutputObject
    >;

    "TaskPosted(uint256,uint256,uint256,address,string,uint32)": TypedContractEvent<
      TaskPostedEvent.InputTuple,
      TaskPostedEvent.OutputTuple,
      TaskPostedEvent.OutputObject
    >;
    TaskPosted: TypedContractEvent<
      TaskPostedEvent.InputTuple,
      TaskPostedEvent.OutputTuple,
      TaskPostedEvent.OutputObject
    >;

    "TaskSettled(uint256,uint256,uint256)": TypedContractEvent<
      TaskSettledEvent.InputTuple,
      TaskSettledEvent.OutputTuple,
      TaskSettledEvent.OutputObject
    >;
    TaskSettled: TypedContractEvent<
      TaskSettledEvent.InputTuple,
      TaskSettledEvent.OutputTuple,
      TaskSettledEvent.OutputObject
    >;
  };
}
