/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DisputeModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "disputes"
      | "openDispute"
      | "owner"
      | "resolveDispute"
      | "resolvers"
      | "setResolver"
      | "taskMarket"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeOpened"
      | "DisputeResolved"
      | "ResolverUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "disputes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openDispute",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "taskMarket",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolvers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskMarket", data: BytesLike): Result;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    buyer: AddressLike,
    disputeURI: string
  ];
  export type OutputTuple = [taskId: bigint, buyer: string, disputeURI: string];
  export interface OutputObject {
    taskId: bigint;
    buyer: string;
    disputeURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    resolver: AddressLike,
    outcome: BigNumberish,
    resolutionURI: string
  ];
  export type OutputTuple = [
    taskId: bigint,
    resolver: string,
    outcome: bigint,
    resolutionURI: string
  ];
  export interface OutputObject {
    taskId: bigint;
    resolver: string;
    outcome: bigint;
    resolutionURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverUpdatedEvent {
  export type InputTuple = [resolver: AddressLike, allowed: boolean];
  export type OutputTuple = [resolver: string, allowed: boolean];
  export interface OutputObject {
    resolver: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisputeModule extends BaseContract {
  connect(runner?: ContractRunner | null): DisputeModule;
  waitForDeployment(): Promise<this>;

  interface: DisputeModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  disputes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, string, string, bigint] & {
        buyer: string;
        opened: boolean;
        resolved: boolean;
        disputeURI: string;
        resolutionURI: string;
        outcome: bigint;
      }
    ],
    "view"
  >;

  openDispute: TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  resolveDispute: TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, resolutionURI: string],
    [void],
    "nonpayable"
  >;

  resolvers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setResolver: TypedContractMethod<
    [resolver: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  taskMarket: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, boolean, boolean, string, string, bigint] & {
        buyer: string;
        opened: boolean;
        resolved: boolean;
        disputeURI: string;
        resolutionURI: string;
        outcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "openDispute"
  ): TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, resolutionURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setResolver"
  ): TypedContractMethod<
    [resolver: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskMarket"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverUpdated"
  ): TypedContractEvent<
    ResolverUpdatedEvent.InputTuple,
    ResolverUpdatedEvent.OutputTuple,
    ResolverUpdatedEvent.OutputObject
  >;

  filters: {
    "DisputeOpened(uint256,address,string)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,uint8,string)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "ResolverUpdated(address,bool)": TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;
    ResolverUpdated: TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;
  };
}
