/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ITaskMarket {
  export type TaskStruct = {
    id: BigNumberish;
    listingId: BigNumberish;
    agentId: BigNumberish;
    buyer: AddressLike;
    paymentToken: AddressLike;
    taskURI: string;
    proposedUnits: BigNumberish;
    quotedUnits: BigNumberish;
    quotedTotalPrice: BigNumberish;
    quoteExpiry: BigNumberish;
    fundedAmount: BigNumberish;
    sellerBond: BigNumberish;
    artifactURI: string;
    artifactHash: BytesLike;
    submittedAt: BigNumberish;
    status: BigNumberish;
    settled: boolean;
  };

  export type TaskStructOutput = [
    id: bigint,
    listingId: bigint,
    agentId: bigint,
    buyer: string,
    paymentToken: string,
    taskURI: string,
    proposedUnits: bigint,
    quotedUnits: bigint,
    quotedTotalPrice: bigint,
    quoteExpiry: bigint,
    fundedAmount: bigint,
    sellerBond: bigint,
    artifactURI: string,
    artifactHash: string,
    submittedAt: bigint,
    status: bigint,
    settled: boolean
  ] & {
    id: bigint;
    listingId: bigint;
    agentId: bigint;
    buyer: string;
    paymentToken: string;
    taskURI: string;
    proposedUnits: bigint;
    quotedUnits: bigint;
    quotedTotalPrice: bigint;
    quoteExpiry: bigint;
    fundedAmount: bigint;
    sellerBond: bigint;
    artifactURI: string;
    artifactHash: string;
    submittedAt: bigint;
    status: bigint;
    settled: boolean;
  };
}

export interface ITaskMarketInterface extends Interface {
  getFunction(
    nameOrSignature: "getTask" | "markDisputed" | "resolveDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
}

export interface ITaskMarket extends BaseContract {
  connect(runner?: ContractRunner | null): ITaskMarket;
  waitForDeployment(): Promise<this>;

  interface: ITaskMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [ITaskMarket.TaskStructOutput],
    "view"
  >;

  markDisputed: TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, resolutionURI: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [ITaskMarket.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<
    [taskId: BigNumberish, disputeURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [taskId: BigNumberish, outcome: BigNumberish, resolutionURI: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
