/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ListingRegistry {
  export type PricingStruct = {
    paymentToken: AddressLike;
    basePrice: BigNumberish;
    unitType: BytesLike;
    unitPrice: BigNumberish;
    minUnits: BigNumberish;
    maxUnits: BigNumberish;
    quoteRequired: boolean;
  };

  export type PricingStructOutput = [
    paymentToken: string,
    basePrice: bigint,
    unitType: string,
    unitPrice: bigint,
    minUnits: bigint,
    maxUnits: bigint,
    quoteRequired: boolean
  ] & {
    paymentToken: string;
    basePrice: bigint;
    unitType: string;
    unitPrice: bigint;
    minUnits: bigint;
    maxUnits: bigint;
    quoteRequired: boolean;
  };

  export type PolicyStruct = {
    challengeWindowSec: BigNumberish;
    postDisputeWindowSec: BigNumberish;
    sellerBondBps: BigNumberish;
  };

  export type PolicyStructOutput = [
    challengeWindowSec: bigint,
    postDisputeWindowSec: bigint,
    sellerBondBps: bigint
  ] & {
    challengeWindowSec: bigint;
    postDisputeWindowSec: bigint;
    sellerBondBps: bigint;
  };
}

export interface ListingRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createListing"
      | "getListing"
      | "identityRegistry"
      | "updateListing"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ListingCreated" | "ListingUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createListing",
    values: [
      BigNumberish,
      string,
      ListingRegistry.PricingStruct,
      ListingRegistry.PolicyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateListing",
    values: [BigNumberish, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateListing",
    data: BytesLike
  ): Result;
}

export namespace ListingCreatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    agentId: BigNumberish,
    listingURI: string,
    paymentToken: AddressLike,
    basePrice: BigNumberish,
    unitType: BytesLike,
    unitPrice: BigNumberish,
    minUnits: BigNumberish,
    maxUnits: BigNumberish,
    quoteRequired: boolean,
    challengeWindowSec: BigNumberish,
    postDisputeWindowSec: BigNumberish,
    sellerBondBps: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    listingId: bigint,
    agentId: bigint,
    listingURI: string,
    paymentToken: string,
    basePrice: bigint,
    unitType: string,
    unitPrice: bigint,
    minUnits: bigint,
    maxUnits: bigint,
    quoteRequired: boolean,
    challengeWindowSec: bigint,
    postDisputeWindowSec: bigint,
    sellerBondBps: bigint,
    active: boolean
  ];
  export interface OutputObject {
    listingId: bigint;
    agentId: bigint;
    listingURI: string;
    paymentToken: string;
    basePrice: bigint;
    unitType: string;
    unitPrice: bigint;
    minUnits: bigint;
    maxUnits: bigint;
    quoteRequired: boolean;
    challengeWindowSec: bigint;
    postDisputeWindowSec: bigint;
    sellerBondBps: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListingUpdatedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    agentId: BigNumberish,
    listingURI: string,
    active: boolean
  ];
  export type OutputTuple = [
    listingId: bigint,
    agentId: bigint,
    listingURI: string,
    active: boolean
  ];
  export interface OutputObject {
    listingId: bigint;
    agentId: bigint;
    listingURI: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ListingRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ListingRegistry;
  waitForDeployment(): Promise<this>;

  interface: ListingRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createListing: TypedContractMethod<
    [
      agentId: BigNumberish,
      listingURI: string,
      pricing: ListingRegistry.PricingStruct,
      policy: ListingRegistry.PolicyStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getListing: TypedContractMethod<
    [listingId: BigNumberish],
    [
      [
        bigint,
        string,
        ListingRegistry.PricingStructOutput,
        ListingRegistry.PolicyStructOutput,
        boolean
      ] & {
        agentId: bigint;
        listingURI: string;
        pricing: ListingRegistry.PricingStructOutput;
        policy: ListingRegistry.PolicyStructOutput;
        active: boolean;
      }
    ],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  updateListing: TypedContractMethod<
    [listingId: BigNumberish, listingURI: string, active: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createListing"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      listingURI: string,
      pricing: ListingRegistry.PricingStruct,
      policy: ListingRegistry.PolicyStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [
      [
        bigint,
        string,
        ListingRegistry.PricingStructOutput,
        ListingRegistry.PolicyStructOutput,
        boolean
      ] & {
        agentId: bigint;
        listingURI: string;
        pricing: ListingRegistry.PricingStructOutput;
        policy: ListingRegistry.PolicyStructOutput;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateListing"
  ): TypedContractMethod<
    [listingId: BigNumberish, listingURI: string, active: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ListingCreated"
  ): TypedContractEvent<
    ListingCreatedEvent.InputTuple,
    ListingCreatedEvent.OutputTuple,
    ListingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ListingUpdated"
  ): TypedContractEvent<
    ListingUpdatedEvent.InputTuple,
    ListingUpdatedEvent.OutputTuple,
    ListingUpdatedEvent.OutputObject
  >;

  filters: {
    "ListingCreated(uint256,uint256,string,address,uint256,bytes32,uint256,uint32,uint32,bool,uint32,uint32,uint16,bool)": TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;
    ListingCreated: TypedContractEvent<
      ListingCreatedEvent.InputTuple,
      ListingCreatedEvent.OutputTuple,
      ListingCreatedEvent.OutputObject
    >;

    "ListingUpdated(uint256,uint256,string,bool)": TypedContractEvent<
      ListingUpdatedEvent.InputTuple,
      ListingUpdatedEvent.OutputTuple,
      ListingUpdatedEvent.OutputObject
    >;
    ListingUpdated: TypedContractEvent<
      ListingUpdatedEvent.InputTuple,
      ListingUpdatedEvent.OutputTuple,
      ListingUpdatedEvent.OutputObject
    >;
  };
}
