/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DisputeModule__factory } from "./DisputeModule__factory";
export { ITaskMarket__factory } from "./ITaskMarket__factory";
